### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/quarto-website-tutorial#17]
Not sure why this gives 404: https://openscapes.github.io/quarto-website-tutorial/quarto-workflows/explore.qmd#confirm

something about a redirect sounds familiar from a previous link fix?

**Comment by stefaniebutland** [comment]
🤔 Julie updated link in this commit https://github.com/Openscapes/quarto-website-tutorial/commit/5265c570e57870cb8765f6bc67a255219bdf3a7d

**Comment by stefaniebutland** [comment]
other pages (RStudio & Jupyter) use html, not qmd in the link`/explore.html#setup-github-action`.

We should harmonize these when fixed

**Comment by jules32** [comment]
Ah yes please update to `.qmd` which is the better approach (which I didn't know before): this will make it possible to make into a pdf or word and still have links (i.e. not reliant on .html).

**Comment by jules32** [comment]
Aha! See https://github.com/Openscapes/quarto-website-tutorial/commit/5265c570e57870cb8765f6bc67a255219bdf3a7d#r78921889

**Comment by stefaniebutland** [comment]
fixed in https://github.com/Openscapes/quarto-website-tutorial/pull/18.

Opening new issue to make other links qmd not html
