### ISSUE TITLE
Update Publish Workflow

### ISSUE THREAD

**Issue by dharaden** [Openscapes/quarto-website-tutorial#35]
I had followed the website tutorial closely and after rendering it on my own machine and pushing to github, my site would not update from the repository that I pulled from. It was still showing the original website without any of my changes. But it was using my github pages URL. 

I ended up renaming and updating the publish workflow that I found here: https://quarto.org/docs/publishing/github-pages.html

This ended up having the action work flawlessly and everything is now looking good! 
This tutorial was great!!! I am so thankful for all of your hard work on this. 

This is also my first time with an "issue" or anything on github. I usually use this for my own projects and don't ever have collaborators so I apologize if this is the incorrect way to go about doing it.

**Comment by jules32** [comment]
Hi @dharaden , thanks for making this issue and so glad that you found this tutorial helpful - and were able to follow up with what you needed on quarto.org. If there is any place in the tutorial you'd recommend us updating, please let us know so we can update it to work more smoothly for others :)

**Comment by dharaden** [comment]
Thank you very much @jules32! Sorry for the delay in getting back to this.

I think updating the [Set up Github Publishing](https://openscapes.github.io/quarto-website-tutorial/explore.html#setup-github-action) section would be helpful. What I had to do was replace that section with information on the [publish GitHub pages](https://quarto.org/docs/publishing/github-pages.html#publish-action) workflow through the Quarto website.

I ended up renaming the "quarto-publish.yml" to just be "publish.yml". I also replaced the code in the action with the following: 
`on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}`

I don't have the technical knowledge to understand what is truly different and why it works that way. So maybe I was doing something wrong in the first place and this just updated it 😄  🤷 

I also recently found that you can use the repository as a template instead of having to fork, which made it easier when I tried making another website. 

Like I said, I am new to this commenting and opening up issues. I just want to be able to contribute however I can (because this is so cool and I hope I bring the same energy of transparency to my own work)!

**Comment by jules32** [comment]
Thanks @dharaden, @ateucher will be following up shortly.

**Comment by ateucher** [comment]
Thank so much for raising this @dharaden! I have updated the workflow specification in a pull request in #39; in my testing this worked.
