### ISSUE TITLE
Dark/light mode is not working

### ISSUE THREAD

**Issue by ghost** [Openscapes/quarto-website-tutorial#37]
Hi!

I noticed that the light-to-dark mode toggle isn’t functioning correctly in the template.

I’ll keep you updated if I find a solution to fix this.

Best regards,
Romain

**Comment by ghost** [comment]
Hi,

I've reviewed the `_quarto.yml` file and noted that its structure is inspired by the configuration used in [this project](https://github.com/sta210-s22/website/blob/main/_quarto.yml). 

To enable a toggle between dark and light modes, you’ll need to import the corresponding CSS files, which you can find in their [repository](https://github.com/sta210-s22/website/tree/main). However, be aware that these CSS files reference certain images. You’ll either need to download these images or remove the lines in the CSS that refer to them.

Unfortunately, I don’t have permission to create a branch or submit a pull request for this change. Please let me know if there's another way I can contribute.

Best regards,

**Comment by jules32** [comment]
Thanks for opening! @ateucher will be following up shortly :)

**Comment by ateucher** [comment]
Thanks for raising this @rlhoussaine! 

@stefaniebutland we have two options here I think:

1: Enable dark and light mode (by creating some css files, or choose two complimentary dark/light themes from [bootswatch](https://bootswatch.com/) like flatly and darkly)
2: Remove [these lines](https://github.com/Openscapes/quarto-website-tutorial/blob/8643cdd5f39e71567ca6ffb374cf828002a46e6e/_quarto.yml#L50-L51) from `_quarto.yml`, which will remove the switch from the website sidebar (below the openscapes logo). 

What do you think?

**Comment by ateucher** [comment]
I lean toward removing the light and dark mode for simplicity, or just specify flatly/darkly. I don't think we want to get into custom css in this tutorial.

**Comment by stefaniebutland** [comment]
I agree with you on option 2 @ateucher. Thanks so much
