### ISSUE TITLE
Add Mine's Quarto-a-day links

### ISSUE THREAD

**Issue by jules32** [Openscapes/quarto-website-tutorial#4]
When she publishes later in June, link to Mine's quarto-a-day tips. Specifically here: 

- [x] https://openscapes.github.io/quarto-website-tutorial/quarto-workflows/#authoring
- [x] example sites on the home index.qmd page

**Comment by stefaniebutland** [comment]
> example sites on the [home index.qmd](https://openscapes.github.io/quarto-website-tutorial/#example-quarto-sites) page

@jules32 These say "A few Quarto websites from Openscapes". Do you want that changed to include others like Mine's and Faylab Manual, or leave as is? 

![Screen Shot 2022-07-15 at 12 53 15 PM](https://user-images.githubusercontent.com/11927811/179301012-1f2bdd90-56c3-44d7-b19a-b3bc675c9b44.png)

**Comment by jules32** [comment]
Yes let's add Mine and FayLab!

**Comment by stefaniebutland** [comment]
fixed in https://github.com/Openscapes/quarto-website-tutorial/pull/18
