### ISSUE TITLE
Improve text about Visual Editor

### ISSUE THREAD

**Issue by jules32** [Openscapes/quarto-website-tutorial#5]
on RStudio page

https://openscapes.github.io/quarto-website-tutorial/quarto-workflows/rstudio.html#visual-editor

A few ideas: 

- click the image to insert an image (screenshot)
- click the table to insert a table
- keyboard shortcuts work for bolding, italics, and also headers! On a Mac, option-command-2 will make a level 2 header. Try it with option-command-1 and option-command-0 for normal text!

**Comment by jules32** [comment]
@stefaniebutland would you be able to build out this section?

**Comment by stefaniebutland** [comment]
pull request https://github.com/Openscapes/quarto-website-tutorial/pull/11

**Comment by stefaniebutland** [comment]
completed.
