### ISSUE TITLE
fix broken link

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/quarto-website-tutorial#7]
On [this page](https://openscapes.github.io/quarto-website-tutorial/transition-from-rmarkdown.html#publishing-notes), this link is broken "Follow instructions from the `[getting started chapter](https://openscapes.github.io/quarto-website-tutorial/first-observations.md#set-up-github-publishing)`."

@jules32 I'm not sure where it should be pointing and I feel like I just followed these instructions.

**Comment by jules32** [comment]
Ah yes it should pint here: https://openscapes.github.io/quarto-website-tutorial/explore.html#set-up-github-publishing!

**Comment by stefaniebutland** [comment]
@jules32 do you mind changing my permissions so I don't have to fork?

**Comment by jules32** [comment]
Yes, done!
